# Generated by Django 5.0.3 on 2024-04-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Smile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("smile", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Molecule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("cas_id", models.CharField(max_length=20)),
                ("url", models.URLField()),
                ("pubchem_url", models.URLField()),
                ("smiles", models.CharField(max_length=200)),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "class_type",
                    models.ManyToManyField(
                        related_name="molecules", to="core.category"
                    ),
                ),
                (
                    "smiles_type",
                    models.ManyToManyField(related_name="molecules", to="core.smile"),
                ),
            ],
        ),
    ]
