# Generated by Django 5.0.3 on 2024-04-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="molecule",
            name="molecular_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="molecule",
            name="molecule_formula",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="molecule",
            name="pubchem_cid",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="molecule",
            name="smiles_iupac",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="molecule",
            name="cas_id",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="molecule",
            name="pubchem_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="molecule",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
