# Generated by Django 5.0.3 on 2024-05-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_molecule_molecular_weight_molecule_molecule_formula_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="molecule",
            old_name="smiles_type",
            new_name="chirality",
        ),
        migrations.RenameField(
            model_name="molecule",
            old_name="remark",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="molecule",
            name="url",
        ),
        migrations.AddField(
            model_name="molecule",
            name="heavy_atom_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="molecule",
            name="hydrogen_bond_acceptor_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="molecule",
            name="hydrogen_bond_donor_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="molecule",
            name="ring_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="molecule",
            name="rotatable_bond_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
