# Generated by Django 5.0.3 on 2024-05-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_smiles_type_molecule_chirality_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Smile",
            new_name="Chirality",
        ),
        migrations.RenameField(
            model_name="chirality",
            old_name="smile",
            new_name="name",
        ),
    ]
