# Generated by Django 5.0.3 on 2024-05-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_smile_chirality_rename_smile_chirality_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="molecule",
            old_name="class_type",
            new_name="category",
        ),
    ]
