# Generated by Django 5.0.3 on 2024-05-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_class_type_molecule_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="molecule",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
