# Generated by Django 5.0.3 on 2024-08-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_molecule_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='InChI',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='molecule',
            name='InChIKey',
            field=models.TextField(blank=True, null=True),
        ),
    ]
